/* Generated by Opal 0.8.1 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require']);
  self.$require("vienna/eventable");
  self.$require("vienna/model");
  self.$require("vienna/adapters/base");
  self.$require("vienna/view");
  return self.$require("vienna/router");
})(Opal);
